
project_id = "ckjxqhapblagwosnchku"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54320
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://lovable.app"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
secure_password_change_enabled = true
enable_signup = true

[storage]
enabled = true
port = 54323
file_size_limit = "50MiB"
s3_max_path_length = 5000

[edge_functions]
enabled = true
port = 54325
