import * as fs from 'fs';

const incompleteQuestions = JSON.parse(
  fs.readFileSync('/Users/julz88/Documents/educoach-prep-portal-2/incomplete-questions-for-regeneration.json', 'utf-8')
);

console.log('=== ANALYZING INCOMPLETE QUESTION GENERATION ===\n');

console.log('Common patterns across all 7 incomplete questions:\n');

const patterns: any = {
  response_type: new Set(),
  generation_method: new Set(),
  generated_by: new Set(),
  test_types: new Set(),
  sections: new Set(),
  sub_skills: new Set(),
  test_modes: new Set(),
};

incompleteQuestions.forEach((q: any) => {
  patterns.response_type.add(q.response_type);
  patterns.generation_method.add(q.generation_method);
  patterns.generated_by.add(q.generated_by);
  patterns.test_types.add(q.test_type);
  patterns.sections.add(q.section_name);
  patterns.sub_skills.add(q.sub_skill);
  patterns.test_modes.add(q.test_mode);
});

console.log('Response Types:', Array.from(patterns.response_type));
console.log('Generation Methods:', Array.from(patterns.generation_method));
console.log('Generated By:', Array.from(patterns.generated_by));
console.log('Test Types:', Array.from(patterns.test_types));
console.log('Sections:', Array.from(patterns.sections));
console.log('Sub-skills:', Array.from(patterns.sub_skills));
console.log('Test Modes:', Array.from(patterns.test_modes));

console.log('\n=== DETAILED GENERATION INFO ===\n');

incompleteQuestions.forEach((q: any, idx: number) => {
  console.log(`${idx + 1}. ${q.test_type} - ${q.section_name} - ${q.sub_skill}`);
  console.log(`   ID: ${q.id}`);
  console.log(`   Response Type: ${q.response_type}`);
  console.log(`   Pattern Type: ${q.generation_metadata?.pattern_type}`);
  console.log(`   Model: ${q.generation_metadata?.model}`);
  console.log(`   Generated: ${q.generation_metadata?.generation_timestamp}`);
  console.log(`   Question: ${q.question_text.substring(0, 100)}...`);
  console.log(`   Correct Answer: ${q.correct_answer}`);
  console.log(`   Answer Options: ${JSON.stringify(q.answer_options)}\n`);
});

console.log('=== KEY FINDING ===');
console.log('ALL 7 questions have response_type: "extended_response"');
console.log('This should ONLY be used for writing/essay questions');
console.log('These are multiple choice questions that were incorrectly marked as extended response\n');
