-- Add visual_svg column to questions table
-- This will store the SVG content generated by Claude web app

ALTER TABLE questions 
ADD COLUMN visual_svg TEXT;

-- Add comment to describe the column
COMMENT ON COLUMN questions.visual_svg IS 'SVG content for visual questions generated by Claude web app';

-- Create index for faster queries on questions with SVG visuals
CREATE INDEX IF NOT EXISTS idx_questions_visual_svg ON questions(visual_svg) WHERE visual_svg IS NOT NULL;

-- Update the type definitions if needed (this is informational)
-- The visual_svg column can contain:
-- - Complete SVG markup (standalone SVG)
-- - Complete HTML with embedded SVG
-- - NULL for questions without visuals 