
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ckjxqhapblagwosnchku.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNranhxaGFwYmxhZ3dvc25jaGt1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDczMDcxOTYsImV4cCI6MjA2Mjg4MzE5Nn0.ufkMeDy0pT5DvjAt0q43HIC3BknQcjA5LXmp9c0E99Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
